### ISSUE TITLE
Preview 10 doesn't retain history properly

### ISSUE THREAD

**Issue by LesterJitsi** [kartik-venugopal/aural-player#106]
As per title, Aural Preview 10 does not retain in history the number of items set in Preferences > History. I can't tell whether this was already present in a previous version.

As the sheer number of features in Aural 4 is growing steadily, I hope I'm not mistaking an intended behavior for an issue 😁 **Maybe the number of recent items is reset when they exceed 25 (or whatever set in Prefs > History)?** 

![Screenshot 2024-09-17 alle 17 35 18_1](https://github.com/user-attachments/assets/d1397f5e-3d94-4fd4-bf36-5fef67446a14)

**Comment by kartik-venugopal** [comment]
Hey Lester, to be honest, that is probably a genuine bug, but that is to be expected in all the v4 preview releases 😄 

Since it is not a mature release, many features (including core features like History) are not working 100%.

That's why I include a disclaimer on the preview release page 😁 

In any case, I will get around to fixing it ... hopefully soon!

**Comment by kartik-venugopal** [comment]
I tried adding more than 25 items with no limit set ... worked fine (retained all 30 something of them).
Then set the limit to 25 in preferences.
Noticed that the oldest ones were deleted such that the most recent 25 items were retained.
Added 2 more items.
Noticed that the 2 oldest items were deleted.

It is working exactly as expected 😄 

You need to first have up to 25 items (or more) for the limit to take effect. Then once the limit is set, it will delete the oldest items as new ones are added.

**Comment by LesterJitsi** [comment]
> It is working exactly as expected 😄
> You need to first have up to 25 items (or more) for the limit to take effect.

Not on my system (Ventura at the time I posted) and not with Preview 10 (I can't test it again right now, but of course I did before posting). Anyway Preview 12 on Sonoma works fine. Thank you!

**Comment by kartik-venugopal** [comment]
> > It is working exactly as expected 😄
> > You need to first have up to 25 items (or more) for the limit to take effect.
> 
> Not on my system (Ventura at the time I posted) and not with Preview 10 (I can't test it again right now, but of course I did before posting). Anyway Preview 12 on Sonoma works fine. Thank you!

Interesting ... I don't remember fixing anything 😄 Thanks for letting me know!
