### ISSUE TITLE
Feature request: integrated bookmark panel

### ISSUE THREAD

**Issue by aqrojo** [kartik-venugopal/aural-player#107]
Hey, awesome project! Keep up the great work!

As a language learner, I was looking for an audio player that lets me create bookmarks. Have you thought about adding an integrated bookmark panel to make it easier to access and edit them? I noticed there’s a menu option for that, but it’s not very usable. I think it would be super useful to have it in the same position as the tracks menu.

Thanks for considering it!

**Comment by kartik-venugopal** [comment]
Hello! Thanks for the great feedback and feature idea.

You definitely can create bookmarks using Aural (you have probably figured this out already) ... using the ellipsis hover menu on the Player or via the Bookmarks menu.

Managing bookmarks (editing them all in one place) is a feature that will come as part of the Library, which will also let you manage Favorites and History. That is still being developed.

I guess you mean a panel showing the list of all bookmarks, and being able to edit the names/descriptions of the bookmarks. Is that right ?

**Comment by aqrojo** [comment]
Hi there!

Thanks for the quick response and for the information about the bookmarks feature! I appreciate that it’s available in v3.

Yes, I believe having it in the same position as the tracks menu would make it more accessible and handy for users.

Thanks again for considering my suggestion, and I’m looking forward to seeing the new Library feature in v4!

**Comment by kartik-venugopal** [comment]
Closing issue as this will come as part of the new Library.
