### ISSUE TITLE
Exclusive Audio Mode

### ISSUE THREAD

**Issue by poeti8** [kartik-venugopal/aural-player#109]
In Exclusive Mode the music player bypasses the operation system interference and connects directly to the output sound device (usually a DAC) to play music.

It's particularly useful when you play Hi-Res music where the sample rate of the track is 96kHz or more. By default, all the sounds in the system share the same output, so macOS has to choose one sample rate and resample everything before sending it to the output device (Default sample rate is usually 44.1kHz and is configured via the Audio MIDI Setup app.) 

So if we have an Exclusive Mode option, we can send music directly to the DAC and make sure it's not shared with any other app on the system. This is to achieve a bit-perfect playback.

This is just a nice-to-have. I'm sure it's not that easy to be implemented. I don't know much myself about the technical aspects of it. Here are some other players that have implemented it, they might have explained it better:

- Audirvana: https://audirvana.com/exclusive-core-player/
- Roon: https://help.roonlabs.com/portal/en/kb/articles/faq-what-s-exclusive-mode
- JRiver: https://wiki.jriver.com/index.php/Exclusive_Access 

You might want to also take a look at [LosslessSwitcher](https://github.com/vincentneo/LosslessSwitcher), although it only changes the output sample rate.

**Comment by kartik-venugopal** [comment]
Thanks for the suggestion. In all honesty, I never knew such a thing existed. Will have to read about it!

**Comment by poeti8** [comment]
> Thanks for the suggestion. In all honesty, I never knew such a thing existed. Will have to read about it!

I just found about it yesterday myself haha. I tried some of the players above (plus Pine Player) and I did notice a difference, however, placebo is always a thing. 

All the good options for macOS that provide this functionality are paid, so if we can have it for Aural that would be really nice.

Thanks!

**Comment by kartik-venugopal** [comment]
Hi, I gave this another look, and to be honest, this is way too advanced for this app. I also don't have experience with anything like this. So I will have to pass on this feature, sorry!

Thanks anyway for the suggestion. Cheers!
