### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Oleg-Chashko** [kartik-venugopal/aural-player#110]
<img width="489" alt="Screen Shot 2024-11-01 at 16 55 46" src="https://github.com/user-attachments/assets/9a2af57f-ee84-4d94-97d3-0884a19cf7cb">
 
[Crash log.zip](https://github.com/user-attachments/files/17600917/Crash.log.zip)

**Comment by kartik-venugopal** [comment]
@Oleg-Chashko - Thanks very much for the bug report! I've fixed the bug and released the fix in the new preview12 build on the release page.

Cheers!
