### ISSUE TITLE
Compact Mode - Color scheme customization doesn't affect window color

### ISSUE THREAD

**Issue by kartik-venugopal** [kartik-venugopal/aural-player#117]

**Comment by kartik-venugopal** [comment]
Fixed in preview18 release.

**Comment by LesterJitsi** [comment]
For me on latest Sonoma and Intel all colors work but Lava... if I did not miss something.

**Comment by kartik-venugopal** [comment]
Hey, I'll take a look. Thanks for the report.

**Comment by kartik-venugopal** [comment]
Just tried it ... works on Modular, Compact, Unified modes (didn't try Menu Bar / Widget modes), so I need more info.

- Which app mode did you try it on ?
- Did you select the color scheme from the main menu bar (on top of the screen) or from the player's pop-up menu ?
- Exact sequence of steps

Thanks!

**Comment by LesterJitsi** [comment]
> * Which app mode did you try it on ?

Modular (multiple windows)

> * Did you select the color scheme from the main menu bar (on top of the screen) or from the player's pop-up menu ?

From menu bar: View > Color scheme. Didn't check from player's pop-up menu though: it works from there!

> * Exact sequence of steps

Click on Aural icon in Dock > View > Color scheme > Lava

> * Also, what color scheme did you have before you tried changing it to LAva ?

Black and green.

**Comment by kartik-venugopal** [comment]
Yup, thanks! Was able to reproduce the issue ... will fix it (along with other stuff) and release in the next few days. Cheers 😄
