### ISSUE TITLE
iOS version can't be compiled?

### ISSUE THREAD

**Issue by azureplus** [kartik-venugopal/aural-player#40]
IOS version can't be compiled?

**Comment by kartik-venugopal** [comment]
Hi, sorry, the iOS version is not ready for any kind of real testing yet. It is just in its very early development / prototype stage, so it may either not compile or be buggy. I still need to do a lot of work on the macOS version before I can get to iOS. It may be ready later in the year.

Anyway, can you share the errors you are getting ? I will see if I can fix them quickly so you can at least run it.
