### ISSUE TITLE
Consider adding MP4 support

### ISSUE THREAD

**Issue by cesss** [kartik-venugopal/aural-player#41]
First of all, congratulations for your player, and thanks, thanks, thanks for developing it!! It has exactly the features I need!

I've read you plan to add MP4 support, but let me bump it, as a part of my music collection is in MP4. I don't know how hard is to add support to it, but consider my vote!!

**Comment by kartik-venugopal** [comment]
Hi, thanks for your feedback and suggestion.

It should not be hard to add MP4 support ... if I'm not mistaken, the audio framework I'm using should just look at the audio stream, completely ignoring the video stream.

I will try to add it soon.

**Comment by kartik-venugopal** [comment]
I've added MP4 and M4V support in [release v3.8.0](https://github.com/kartik-venugopal/aural-player/releases/tag/v3.8.0). Try it out and please let me know if it works as expected.

Note - Only the common MP4 audio formats are currently supported, i.e. AAC, AC-3 (macOS native formats). MP4 with Vorbis audio, for instance, is not supported. But AAC is the most common audio format in MP4 files so this should be good enough for you, I think.

BTW, if you come across an MP4 file in your collection that doesn't work, do let me know what audio format it contains. It would be interesting for me to know for future reference and also so I can add support for it in the future.

**Comment by cesss** [comment]
It works!!!!!! 🚀 🚀 🚀 

Thank you very very much!!! Yes, it seems my MP4 files use the codecs that you currently support!! I tested several of them, and all play fine!

By the way,  I'll be using it in Monterey this week, when I update my MBP. For the moment I'm using 3.3.1 because your latest releases have UI glitches in High Sierra (for example, the windows don't appear on start, you need to bring them up using the menu bar. And the current effect underline effect is not updated)... don't worry, just UI glitches that you cannot debug right now, and that I guess don't show in >=BigSur

Feel free to close the issue, because 3.8.0 plays MP4 fine on High Sierra. If I experience any issue in Monterey, I'll tell you.

Thanks, thanks, thanks!!!

**Comment by kartik-venugopal** [comment]
Great, thanks for letting me know !

Yes, unfortunately, I am no longer able to debug issues on older systems. Plus, Apple makes it quite hard to install older OS versions, and it's just not worth the effort.
