### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by lijuncode** [kartik-venugopal/aural-player#53]
Playing songs by FFmpegScheduler can cause memory leaks, and the memory usage will continue to grow.
![截屏2023-03-17 21 30 57](https://user-images.githubusercontent.com/10102528/225918897-c96da74f-fc61-4391-8710-cb30a44d2153.png)

**Comment by lijuncode** [comment]
![截屏2023-03-17 21 41 29](https://user-images.githubusercontent.com/10102528/225921521-75665025-1862-41b0-aaf4-8609ec9279f2.png)

**Comment by kartik-venugopal** [comment]
Hi @lijuncode , thank you !

Yes, I am already aware of this issue 😄  I actually spent a lot of time trying to fix it, but was not able to figure out where exactly the leak is happening. I tried many different solutions, but just didn't have any luck.

But, from what I remember, the leak is relatively minor in terms of the amount of memory leaked ... after loading several tracks into FFmpegScheduler, only a few MB (less than 10, I think) were leaked. And given that most Macs today have a minimum of 8 GB memory and often more than that, I gave up on trying to fix it.

Of course, I do acknowledge that this is a genuine issue. I just haven't been able to fix it and the consequences to the user seem minor enough to not be a significant issue.

If you can figure out a fix, I'd be happy to accept your pull request 😄 

Cheers,
Kartik

**Comment by kartik-venugopal** [comment]
Released in [v3.15.0](https://github.com/kartik-venugopal/aural-player/releases/tag/v3.15.0).
