### ISSUE TITLE
Make text on music details panel copyable

### ISSUE THREAD

**Issue by XhstormR** [kartik-venugopal/aural-player#55]
It would be handy if the text on the music details panel could be copied:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/10527522/229340908-8fdc4dce-3799-4299-bba3-a747fcf71fb6.png">

**Comment by kartik-venugopal** [comment]
Hi @XhstormR, thanks for the suggestion. I will implement this in the next release. Hopefully soon.

**Comment by kartik-venugopal** [comment]
Implemented and released in [v3.15.0](https://github.com/kartik-venugopal/aural-player/releases/tag/v3.15.0).
