### ISSUE TITLE
Request to add the ability to sort the list by file modification time

### ISSUE THREAD

**Issue by XhstormR** [kartik-venugopal/aural-player#56]
It would be nice to be able to sort the list by file modification time
<img width="549" alt="image" src="https://github.com/kartik-venugopal/aural-player/assets/10527522/4111653c-4078-464d-b3a3-f709fd7dc080">

**Comment by kartik-venugopal** [comment]
You got it, my friend 😄  Will implement.

**Comment by kartik-venugopal** [comment]
Implemented and released in [v3.18.0](https://github.com/kartik-venugopal/aural-player/releases/tag/v3.18.0).

By the way, do you live in Hotel California ? 😁

**Comment by XhstormR** [comment]
@kartik-venugopal Ha, you got me!😁
