### ISSUE TITLE
Aural 3.18.0 displays playlists at random

### ISSUE THREAD

**Issue by LesterJitsi** [kartik-venugopal/aural-player#57]
It's a little intricate issue. I always have my playlists sorted by _Artist,Album, and Disc#/Track#_ and set _Preferences > Playlist_ to _Remember playlist from last app launch_ and _Remember view from last app launch._ Actually I'm realizing now I didn't have to use "Sort playlist" because all needed info is included in the .m3u file I regularly use. I noticed that:

1. Aural retains correct view options if I quit and then restart the app without making any change to the current playlist.
2. If I clear the playlist and then double-click or drag a .m3u file, the new playlist is sorted as if shuffle mode were on (of course it isn't). I assume shuffle mode as I can't see any sensible order in the track sequence. I mean track names appear seemingly at random. I'm attaching 2 screens. The same happens if I ctrl-click a .m3u file and open with Aural 3.18.0 (but not with 3.16.0).

Aural 3.16.0 works fine. I didn't test 3.17.0. Running macOS 10.14.6.

Off topic, while writing this note I had to struggle with Aural preferences and sort playlist windows which stubbornly stayed in the foreground 😉 [#37](https://github.com/kartik-venugopal/aural-player/issues/37)

Thanks in advance
![Aural 3 16 0 correct order_1](https://github.com/kartik-venugopal/aural-player/assets/25617355/c517439e-8c9e-4545-b78a-e755372b782b)
![Aural 3 18 0 at random_1](https://github.com/kartik-venugopal/aural-player/assets/25617355/cd393596-f8ed-4966-b997-a68b40f12495)

**Comment by kartik-venugopal** [comment]
Hey @LesterJitsi , thanks for reporting this bug. This is pretty bad and needs to be fixed.

It's strange that 3.16 works okay but 3.17 does not. I have a gut feeling that it is related to a warning I received from Xcode (the program editor) when building 3.17.

I will take a look now, and keep you updated on the fix.

Thanks,
Kartik

**Comment by kartik-venugopal** [comment]
Found the bug ... it has specifically to do with how the M3U playlist tracks are added to the playlist. I introduced this bug during a partial (unfinished) implementation of CUE Sheet (playlist) support.

Fixing it now ...

**Comment by kartik-venugopal** [comment]
Fixed and released in [v3.19.0](https://github.com/kartik-venugopal/aural-player/releases/tag/v3.19.0). BTW, I've also fixed the other one you mentioned: #37, in this release.
