### ISSUE TITLE
Scroll bar thumb missing in playlist window

### ISSUE THREAD

**Issue by skillt3ch** [kartik-venugopal/aural-player#60]
There is no "thumb" in the playlist scroll bar which makes scrolling large playlists slow and cumbersome.

**Comment by kartik-venugopal** [comment]
Hi, thanks for the issue report. It's just that I'm away from the project for a while due to being very busy, but I've noted your request. Cheers!

**Comment by kartik-venugopal** [comment]
Implemented in [v3.20.0](https://github.com/kartik-venugopal/aural-player/releases/tag/v3.20.0)!

**Comment by skillt3ch** [comment]
> Implemented in [v3.20.0](https://github.com/kartik-venugopal/aural-player/releases/tag/v3.20.0)!

Thank you for your hard work!
