### ISSUE TITLE
Request: Cmd+A to select all items in a playlist

### ISSUE THREAD

**Issue by skillt3ch** [kartik-venugopal/aural-player#61]
Can you please add a feature to select all playlist items with the key command Cmd+A? I know currently all items can be selected with shift clicking the first and last items, however a keyboard shortcut would be much faster and more convenient, especially for large playlists.

**Comment by kartik-venugopal** [comment]
Makes sense. Will implement this one soon because it should be quite easy and quick,

**Comment by kartik-venugopal** [comment]
Implemented in [v3.20.0](https://github.com/kartik-venugopal/aural-player/releases/tag/v3.20.0)!

**Comment by skillt3ch** [comment]
> Implemented in [v3.20.0](https://github.com/kartik-venugopal/aural-player/releases/tag/v3.20.0)!

All these new changes are making big improvements!
