### ISSUE TITLE
Request: support for tracker module formats (.it, .xm, .mod, .s3m)

### ISSUE THREAD

**Issue by skillt3ch** [kartik-venugopal/aural-player#62]
Can you please add compatibility for tracker module formats? A lot of chip tunes and old video game music use the following formats:

* IT
* XM
* MOD
* S3M

**Comment by now-its-dark** [comment]
More broadly, is there any intention of including some form of plugin/extension system in the future? That is one of the great strengths of winamp- being able to add support for new formats etc.

**Comment by kartik-venugopal** [comment]
I was able to add support via libopenmpt and was able to play back a bunch of tracker module files. But, I'm having some trouble with the packaging of libopenmpt (and its dependencies). Hopefully I should be able to sort this out soon.

**Comment by now-its-dark** [comment]
That's awesome! 🙏 It would be pretty fantastic if MIDI formats were possible someday as well, the available options are fairly sparse for MIDI playback on external devices (as in, not using soundfonts, but rather pointing the data at one or more available MIDI ports).

**Comment by kartik-venugopal** [comment]
@skillt3ch - Implemented and released in [v3.21.0](https://github.com/kartik-venugopal/aural-player/releases/tag/v3.21.0).

Please try it out and let me know if it works. Thanks.

**Comment by kartik-venugopal** [comment]
> More broadly, is there any intention of including some form of plugin/extension system in the future? That is one of the great strengths of winamp- being able to add support for new formats etc.

Wow, that is quite a stretch at the moment ... I wouldn't even know how to begin to implement something as complex as that. But, I've noted it down as something to keep an eye out for.

Cheers!

**Comment by skillt3ch** [comment]
> @skillt3ch - Implemented and released in [v3.21.0](https://github.com/kartik-venugopal/aural-player/releases/tag/v3.21.0).
> 
> Please try it out and let me know if it works. Thanks.

Works perfectly, thank you for implementing it!
