### ISSUE TITLE
suggest new app icon

### ISSUE THREAD

**Issue by VisualisationExpo** [kartik-venugopal/aural-player#63]
I'd like to suggest a new app icon to replace the rather dated one.  If interested, let me know. You can use it freely for Aural.
If not interested I'll just upload it on deviantart for instance.

<img width="125" alt="image" src="https://github.com/kartik-venugopal/aural-player/assets/86615159/f1ae6c6d-9268-4f42-b9f1-acadc070a7d3">

**Comment by kartik-venugopal** [comment]
Hi @VisualisationExpo - Yes, I would love to use your icon. I will give you credit on the home page (contributors section) and on the app release page. Thanks !

**Comment by VisualisationExpo** [comment]
Can I send it somehow as an ICNS in an e-mail? is that preferred?

**Comment by VisualisationExpo** [comment]
[macOS 'Aural' Big Sur Icon.icns.zip](https://github.com/kartik-venugopal/aural-player/files/12689594/macOS.Aural.Big.Sur.Icon.icns.zip)

I uploaded here instead.. enjoy. If there's anything that seems off to you then reach out.

**Comment by VisualisationExpo** [comment]
Alternate icon on the left in the screenshot next to the already shared icon. 

<img width="199" alt="image" src="https://github.com/kartik-venugopal/aural-player/assets/86615159/e67e0402-4b6f-47f5-b7e4-5617e1e17474">
[macOS 'Aural' Big Sur Icon 3.icns.zip](https://github.com/kartik-venugopal/aural-player/files/12689838/macOS.Aural.Big.Sur.Icon.3.icns.zip)

**Comment by kartik-venugopal** [comment]
Implemented and released in [v3.22.0](https://github.com/kartik-venugopal/aural-player/releases/tag/v3.22.0)!

Provided you credits for the icon on the release page and on the main README page [here](https://github.com/kartik-venugopal/aural-player#contributor-attributions).

Cheers!
