### ISSUE TITLE
[bug] menu bar mode icon issue

### ISSUE THREAD

**Issue by BillGoldenWater** [kartik-venugopal/aural-player#67]
after update, to v3.22.0 the icon of menu bar mode has some display issue, looks like it's has a wrong size

<img width="38" alt="image" src="https://github.com/kartik-venugopal/aural-player/assets/53564043/ba4b41dc-c1b7-4797-86f9-28fb6e97ee20">
<img width="38" alt="image" src="https://github.com/kartik-venugopal/aural-player/assets/53564043/f133ebe3-af41-4bc3-b03d-3b98e423672a">

**Comment by kartik-venugopal** [comment]
Hi, thanks for the bug report ... good catch!

Will release the fix in a couple of days (need to test some other changes that have gone into this new release). 

Cheers!

**Comment by kartik-venugopal** [comment]
Implemented a fix and released it in (v3.24.0)[https://github.com/kartik-venugopal/aural-player/releases/tag/v3.24.0].
