### ISSUE TITLE
Not Issues

### ISSUE THREAD

**Issue by HZHCoder1990** [kartik-venugopal/aural-player#68]
Awesome!

**Comment by kartik-venugopal** [comment]
Thank you very much for the positive feedback :-)

Cheers!

**Comment by runeflobakk** [comment]
I have been looking for a player like this for Mac for years, so big thank you from me as well! 🏆  Excited for what's to come in the 4.0 release!
Commenting here to avoid noise in the open issues :)

**Comment by kartik-venugopal** [comment]
@runeflobakk - Thank you so much for your feedback. It's comments like yours that give me the motivation to continue my work on this project, despite a busy schedule :)

Cheers!
