### ISSUE TITLE
Does not start with empty playlist if "append files/folders" is selected

### ISSUE THREAD

**Issue by LesterJitsi** [kartik-venugopal/aural-player#69]
The title is self-explanatory. I don't know if this is intended, but when I start Aural from the Dock it behaves as expected (see screenshot with playlist settings). If I quit Aural and then double-click a .m3u file, Aural starts and it appends the new tracks to the last played playlist. The "ghost" playlist does not appear in _History > Recently added_, but its tracks appear in _History > Recently played_.

Aural 3.24.0 on Ventura 13.6. Thanks in advance.

![Screenshot 2023-10-21 alle 19 15 05_2](https://github.com/kartik-venugopal/aural-player/assets/25617355/3cceb6df-58b6-4e6b-aeb7-9473f89c7258)

**Comment by kartik-venugopal** [comment]
Thanks! Yup, reproduced the bug and found the issue in the code. Will fix soon :)

Cheers !

**Comment by kartik-venugopal** [comment]
Released a fix in v3.24.1. Please try it out and let me know if it works.

BTW, I am not putting in much work on v3.x these days as I am trying to get v4.0 out ... hopefully in a few months! So, if I get a bug report on v3.x, I would do the bare minimum to fix it without too much testing on my end.

If and when by some miracle I do get v4.0 out, I would appreciate you trying it out and giving me some feedback.

And thanks again :)
