### ISSUE TITLE
Cannot add to playlist if folder includes cue file

### ISSUE THREAD

**Issue by sirlaurie** [kartik-venugopal/aural-player#72]
I have some albums include cue file, if I add the folder to playlist window, the app just stuck. if I move cue file out of folder and add it to playlist again, it just works.

**Comment by kartik-venugopal** [comment]
Hi, thanks for the bug report! I have investigated it and discovered the problem. I will release a fix soon.

Cheers!

**Comment by kartik-venugopal** [comment]
I've released a fix in: [the latest v3.25.2 release](https://github.com/kartik-venugopal/aural-player/releases/tag/v3.25.2).

Please try it out and let me know if the problem has been solved.

Cheers!

**Comment by sirlaurie** [comment]
It works! Thanks for this great work
