### ISSUE TITLE
Aural-player starts playing by itself

### ISSUE THREAD

**Issue by ishikawa206** [kartik-venugopal/aural-player#75]
Thanks for always developing Aural-player.
I am a Mac user and have noticed an unusual phenomenon with aural-player.
That is, when I receive FaceTime, one of Mac apps, Aural-player starts playing by itself.
Could you please investigate this once?

**Comment by kartik-venugopal** [comment]
Hi, thanks for the bug report. I have never used FaceTime before, but I will try to reproduce the bug and fix it.

I may need more information from you later, but I will first try to investigate it myself.

**Comment by LesterJitsi** [comment]
I make an unrequested remark as it's an unusual issue. I found a couple of matches dating back to 2019:

https://discussions.apple.com/thread/250386455?page=2&sortBy=best
https://community.spotify.com/t5/Desktop-Mac/Facetime-call-START-Spotify-playing-on-my-mac/td-p/4773214

Given that lots of bugs in macOS have never been fixed, Aural might not be the culprit.

**Comment by kartik-venugopal** [comment]
> I make an unrequested remark as it's an unusual issue. I found a couple of matches dating back to 2019:
> 
> https://discussions.apple.com/thread/250386455?page=2&sortBy=best https://community.spotify.com/t5/Desktop-Mac/Facetime-call-START-Spotify-playing-on-my-mac/td-p/4773214
> 
> Given that lots of bugs in macOS have never been fixed, Aural might not be the culprit.

@LesterJitsi - Wow, thank you so much for the info! I never would have suspected that because I never use FaceTime :)

Yes, macOS definitely introduces bugs from time to time. Will keep this particular bug in mind when debugging this issue.

Cheers!
