### ISSUE TITLE
Tracker module support

### ISSUE THREAD

**Issue by RC128tech** [kartik-venugopal/aural-player#81]
macOS does not know that Aural can play .xm, .mod and other tracker files.
If you want to set it as default player, you have to select 'all applications'.

A stereo pan function for tracker files would be useful. Especially Protracker modules are having
a very heavy channel seperation, so blending the channels together using a slider would be great.

Is it difficult to implement support for .sid and .psid files of the Commodore 64?

Greets

Edit: Protracker .mod files don't have an Aural project icon, it's only a white sheet.

**Comment by kartik-venugopal** [comment]
Hmm, this is a bit ambitious at the moment :-) But when I have more time, I will look at the effort involved and give you a proper answer.

Just from glancing at the request, I'm guessing I would have to defer these new features to a minor version release of v4 (i.e. v4.x).

**Comment by RC128tech** [comment]
The old version of Vox I used had a whole section for Tracked Music in the Preferences, including different Surround modes. This enhanced the quality of tracker modules a lot. But surround modes could make it the sound worse for normal sound.

Including SID sound files is rather difficult, but it would be cool because multiformat players can't play these.
I guess there are some routines out there.

**Comment by RC128tech** [comment]
My recommendation for Version 4:

- Use a standard macOS GUI for the Preferences window. It looks better if you have a light macOS theme as default.
- As I started Aural the first time, I immediately remembered WinAmp. Can you make Aural compatible to WinAmp themes?
- I can do a German translation for Aural.

**Comment by RC128tech** [comment]
Which file formats can Aural play actually? I also need the suffixes.

**Comment by kartik-venugopal** [comment]
Thanks for the feedback. I am adressing such concerns in v4.

File formats: https://github.com/kartik-venugopal/aural-player/wiki/Features#audio-formats

**Comment by kartik-venugopal** [comment]
Tracker module support has been dropped in v4 because it is not possible to cross-compile libopenmpt on a single machine for both arm64 and x86. I have already spent days of effort trying to figure this out, and it's just not worth any further effort.
