### ISSUE TITLE
Folder selection window crashes

### ISSUE THREAD

**Issue by RC128tech** [kartik-venugopal/aural-player#83]
In the Playlist section you have two playlist options:

Load playlist from file
Load tracks from folders

If you click on 'Browse' to open the file/directory window, it is possible to close the the window with Cancel
one, maybe two times, then the window stays open constantly. It's neccessary to kill the process Aural.

System: macOS 14.4.1 on MacBookPro11,5 using OpenCore Legacy Patcher.

**Comment by kartik-venugopal** [comment]
Hi, thanks for all your issue reports. I have been away from the project for a while, but will look into this bug hopefully in the next few days.

**Comment by kartik-venugopal** [comment]
I'm unable to reproduce the issue on my Macbook Pro 15,11 running macOS 14.2.1. Tried many times.

**Comment by RC128tech** [comment]
Try this:

1. Open Preferences window
2. Click on the 'Browse' button
3. The directory window can't be moved and doesn't react to any mouse click
4. Click on the desktop or another window
5. Click back on the directory window and it reacts normally

I'm not using a window enhancer like Default Folder X.

**Comment by LesterJitsi** [comment]
FWIW I can't reproduce neither one on latest Ventura (MacBook Air8.2), with or without Default Folder X.

**Comment by RC128tech** [comment]
But that's not Sonoma 14.4.1. There can be minor changes in the OS which causes bugs.

@LesterJitsi 

You also can upgrade your MacBookAir8,2 to a 4 TB SSD and Sonoma 14.4.1.
https://github.com/dortania/OpenCore-Legacy-Patcher

**Comment by LesterJitsi** [comment]
Of course, it was just my 2 cents. Also running Sonoma on usupported hardware may cause issues. That's why I'd never upgrade my Mac the way you suggested before editing your post.

**Comment by RC128tech** [comment]
I tested Aural on my OSx86 machine running macOS 10.14.6 and it didn't have that bug.
This system is working stable for 12 years.

OpenCore Legacy Patcher is a bootloader with its origins from the OSx86 scene.
It has a more sophisticated bootloader than the one from Apple, allows to create an USB install sticks
and provides the drivers Apple removed in newer OS X versions. It's a really safe method.
It also allows Non-Metal graphic cards to work and has support for Non-Apple-SSDs.
The 4 TB Kingston SSD I'm using is more as double as fast, 2,5 GB/s write and 2 GB/s read.
