### ISSUE TITLE
Fast forward or backward is glitchy

### ISSUE THREAD

**Issue by yan-8** [kartik-venugopal/aural-player#86]
When fast-forwarding or rewinding an audio track (with right or left arrows) that has a long duration (for example, 60 minutes), the fast-forwarding takes a very long time with brakes or glitches (please see video below).

Environmant:
OS Version - 13.6.7

https://github.com/kartik-venugopal/aural-player/assets/23197048/374c358e-4cf6-48bc-80cc-f821555e0475

**Comment by kartik-venugopal** [comment]
Hi, thanks for the issue report. 

I need some info ... could you do me a favor ... view detailed track info for that track, go to the "Audio" tab of the information popup, and take a screenshot of it.

This issue could be related to how Aural uses FFmpeg to play non-natively supported tracks.

Thanks!

**Comment by yan-8** [comment]
Yes, please:
￼

**Comment by kartik-venugopal** [comment]
Did you attach a screenshot ? I don't see it 😄 Also, your Aural Player version ? Thanks!

**Comment by yan-8** [comment]
Yes, I attached a screenshot. Check it, its below of my message. Or I can send again:
￼

**Comment by yan-8** [comment]
Version is: 3.25.2
￼

**Comment by yan-8** [comment]
I guess I understood, I did it via built-in "Mail" client. So let me send via GitHub page.
<img width="569" alt="2024 06 14 - 14 53 20" src="https://github.com/kartik-venugopal/aural-player/assets/23197048/e8c689d8-39c8-4394-82df-3b35f7c6f4c1">

**Comment by kartik-venugopal** [comment]
Got it, thanks! Will take a look ...

**Comment by kartik-venugopal** [comment]
Hi, I have found the issue. It is likely a bug in FFmpeg ... when I replaced the FFmpeg library version with a different one, it worked.

I will give you a new working app build soon ... in the next hour or 2. Stay tuned.

**Comment by kartik-venugopal** [comment]
Hello, please find attached a new working build ... please try it out and let me know if it works for you. Thanks!
[AuralPlayer-3.26.0.zip](https://github.com/user-attachments/files/15844212/AuralPlayer-3.26.0.zip)

**Comment by yan-8** [comment]
I will check it up soon.

**Comment by yan-8** [comment]
I think your last buid is amazing!
Thank you for your bugfix. 🤗
https://github.com/kartik-venugopal/aural-player/assets/23197048/1afb138f-3ae2-41da-ba80-c32283c2b0bc

**Comment by kartik-venugopal** [comment]
Great! Glad to hear that. I like that Ace of Base album too 😁 

Closing this ticket. Cheers!

**Comment by kartik-venugopal** [comment]
Just one more comment - I will not be releasing this fix in a v3 release, but you can just continue using the build I gave you ... the fix will also go into v4. Watch out for the v4 release coming later.
