### ISSUE TITLE
UI - Track info pop-up window under the Effect panel

### ISSUE THREAD

**Issue by yan-8** [kartik-venugopal/aural-player#87]
As a user I want to see track info pop-up window over the windows.
Expected res:
Over the windows / panels.

Actual res:
Under the windows / panels.
https://github.com/kartik-venugopal/aural-player/assets/23197048/a98252f9-01a3-49ab-b6e9-c0275dc94aab

**Comment by kartik-venugopal** [comment]
Hi, thanks for the issue report. This issue has gone away in v4 because track info is displayed in a separate window in v4, so I am closing this issue.
