### ISSUE TITLE
Effects panel - > Audio Units menu, double click for turn on / off some plugins

### ISSUE THREAD

**Issue by yan-8** [kartik-venugopal/aural-player#88]
I think much better would be when some plugins can be clicked just one click for turn on or off the plugin. Current behavior is that we need execute double click. Also highlighting is not appropriate appearing when user turned on or off the plugin. Usually when plugin turned on the hightlight is blue color, if turned off is grey (like don't work).
Thank you for your work!

Actual res:
https://github.com/kartik-venugopal/aural-player/assets/23197048/fc323a94-19d0-43b3-8cea-ff3cc97e6a8d

**Comment by kartik-venugopal** [comment]
This issue has been fixed in v4 (a while ago). Try now with v4 preview.
