### ISSUE TITLE
Allow windows to be de-magnetized

### ISSUE THREAD

**Issue by yan-8** [kartik-venugopal/aural-player#91]
Hi dear developer!
Could you please help me with small issue, I can't understand how to demagnetize an additional window like AU Window? Please see a video below.
https://github.com/kartik-venugopal/aural-player/assets/23197048/691040cf-f207-4c15-a35e-89819cc5f683

**Comment by kartik-venugopal** [comment]
Ah, you mean when you move the main window, the AU window should not move with it ? Unfortunately, there is no way to do that currently. This behavior is as designed ... all windows of the app are children of the main window, so they will move when the main window moves. You will need to move the AU window alone by itself.

If you want to reposition the AU window, I suggest first moving the main window and then moving the AU window by itself.

**Comment by yan-8** [comment]
😩

**Comment by kartik-venugopal** [comment]
I will add a preference in v4 to let the user choose to demagnetize a window. Happy ?

😄

**Comment by yan-8** [comment]
Ohh that's amazing, thank you! You made my weekend. 😉👨🏻‍💻🙂

**Comment by yan-8** [comment]
Hey! Unfortunately I cannot run it.
![Uploading 2024.07.31 - 21.24.51.png…]()

**Comment by kartik-venugopal** [comment]
Hey, I will try to take a look this weekend

**Comment by kartik-venugopal** [comment]
Hey, this has been implemented., I will release it soon.
