### ISSUE TITLE
Fast double click on a file just adds file on playlist except of playing in the player

### ISSUE THREAD

**Issue by yan-8** [kartik-venugopal/aural-player#92]
Hello!
Could you please help me, how to turn off the feature when if a user fastly clicks on file from OS the file is playing?
Current behavior is if a user fastly clicks on file from OS the file just adds to playlist and not playing which is a bit confusing. I was trying find a trigger in settings but I did not find it. Please see video example below, I compared with INNA player for better understanding what I am talking about:
https://github.com/user-attachments/assets/bdac5a21-7a09-4668-bf81-017a7c016326

**Comment by kartik-venugopal** [comment]
Hey, yes, there is a setting in Preferences > Playback, under the Autoplay section. Look for the caption: "After adding tracks, play first added tracks."

If you don't want the files to be appended to the playlist ... if you want to replace everything in the playlist with your clicked file, look under Preferences > Playlist under the caption "When files/folders are added via Open With"

If this doesn't help, I'll send you screenshots tomorrow ... bit late, going to sleep.

**Comment by kartik-venugopal** [comment]
Closing this issue as I gave a solution in my earlier comment. Reopen if you still have a problem with this one.

**Comment by yan-8** [comment]
Thank you for your help. Unfortunately I tried as you told me but it doesn't work.
My settings below:
![2024 07 17 - 22 01 08](https://github.com/user-attachments/assets/8a4a21d2-667f-4936-bef7-d3ec8bbba6d4)
![2024 07 17 - 22 01 15](https://github.com/user-attachments/assets/835cb5a4-7ec1-48ba-baf0-1cbcdd962e09)

**Comment by kartik-venugopal** [comment]
This works in v4 (v3 is archived). Please try one of the preview builds.
