### ISSUE TITLE
AU Effect disapears after clicking on Close button

### ISSUE THREAD

**Issue by yan-8** [kartik-venugopal/aural-player#93]
Hello dear developer!
Please see on a bug video below:

https://github.com/user-attachments/assets/b19bae4c-bcd3-4c2d-b839-808ceb7c86aa

**Comment by kartik-venugopal** [comment]
This is intended behavior when running in Compact mode :-)

**Comment by yan-8** [comment]
But AU window is disappeared. I guess it's not intended behavior, isn't it?

**Comment by kartik-venugopal** [comment]
It is intended ... when you close the effects panel, the app assumes you are finished with the effects (in Compact mode) ... keep in mind that the Compact app mode is a limited-interaction app mode ... this means that the app will make certain assumptions about how the user will interact with it ... it will not be as full-featured as the Modular and Unified app modes ... those modes should allow all core functionality without restrictions, but Compact app mode simply does not allow multiple windows to hang around ... it is meant to be ... "Compact" 😁

**Comment by kartik-venugopal** [comment]
... but I guess you like to monitor the sound with your AU window ? In that case, I will think of a way to allow this in Compact mode as well... it was not how it was intended to be in Compact mode, but let's see

**Comment by yan-8** [comment]
> ... but I guess you like to monitor the sound with your AU window ? In that case, I will think of a way to allow this in Compact mode as well... it was not how it was intended to be in Compact mode, but let's see

Yes, exactly, thank you so much. I see that in current version is working well in Compoct mode. I like it.

**Comment by yan-8** [comment]
Sorry @kartik-venugopal, when I was testing last build I found that it does not work. Also I found double main window. It looks like bug.
<img width="676" alt="2024 08 11 - 23 48 28" src="https://github.com/user-attachments/assets/f0dfd9a7-c8b6-45ae-9441-c80ddd53ce56">

**Comment by yan-8** [comment]
Log file, should be useful.
[aural.log](https://github.com/user-attachments/files/16576215/aural.log)

**Comment by kartik-venugopal** [comment]
Hey, can you please give me the steps to reproduce the double window in Compact Mode ? I am not able to reproduce that. Thanks.

**Comment by yan-8** [comment]
It's to hard. I cannot to reproduce it. I did not understand what exactly hapend in that time.

**Comment by kartik-venugopal** [comment]
Fixed, AU windows will now stay open. Will release soon.
