### ISSUE TITLE
"The blues" Color Scheme is absent

### ISSUE THREAD

**Issue by yan-8** [kartik-venugopal/aural-player#94]
"The blues" color scheme does not have a configs.
![Aural - 2024 07 20 2](https://github.com/user-attachments/assets/d64dcd9a-6710-4d7e-8c90-278dc83a9dd5)

**Comment by kartik-venugopal** [comment]
Thanks. YEs, as I said on the preview release page, the preview build is incomplete and there are known issues. Will be fixed in the actual v4 release.

BTW, The Blues color scheme is now gone.

**Comment by yan-8** [comment]
Understood, thank you!
