### ISSUE TITLE
Waveform progress bar

### ISSUE THREAD

**Issue by dcocharro** [kartik-venugopal/aural-player#97]
The waveform progress bar is a feature request because I believe this allows the user to seamlessly find and skip to certain parts of the song easily.
It would be nice to have this as a user-defined option.
Thank you

**Comment by kartik-venugopal** [comment]
Thanks for the feature request. I will try to get it done. The waveform progress bar would probably be shown in a new separate window.

**Comment by kartik-venugopal** [comment]
Released in the latest "preview5" build (get it from the latest release page). Let me know how you like it. 

Cheers!
