### ISSUE TITLE
Don't clear playlist after drag and drop new music file

### ISSUE THREAD

**Issue by yan-8** [kartik-venugopal/aural-player#99]
@kartik-venugopal hey!
Could you please to help me with, how to clear a body of Play Queue window (playlist) when a user adds new file to main player window? (video below)

https://github.com/user-attachments/assets/857a9efb-345b-4e71-b755-1647646f6344

**Comment by kartik-venugopal** [comment]
Hey, I see that it's not working currently ... I will fix it soon.

**Comment by kartik-venugopal** [comment]
Fixed, will release soon.
